label badEnd_one:
    j "bueno ya estamos aqui, es lugar muy oscuro como era de esperarse"
    i "ahi, mira el centro del edificio"
    i "ahi pongo todas las cosas que tomo de la gente "
    i "y en 2 horas aparece dinero en el mismo lugar"
    j "quieres decir que mis cosas estan el centro de ese asqueroso edificio?"
    i "si"
    j "lo que faltaba"
    i "adelante ve"
    j "no tienes que decirmelo, ire por ellas ya mismo"
    j "ahora que miro de cerca, son un monton de cosas reunidas al azar, sin ningun criterio"
    i "jujuju"
    j "supongo que mis cosas estaran en el en la parte mas alta"
    i "jajaja"
    j "ahi esta, dios, no fue tan dificil, solo tuve que escalar un poco"
    i "jajajajajjajajajajaa!!!!"
    j "oye que es lo que pasa porque tanto alboroto por alla?"
    i "no puedo creer que hayas sido tan ingenuo, por dios"
    i "y pensar que gente como tu existe"
    i "te recomiendo que pienses de nuevo lo que has hecho, y vuelve a empezar"

